name: Publish Package to Github Packages & upload bundle to S3
on:
  release:
    types: [published]
  # push:
  #   branches: [max_monthly_failures_per_card_reference]
env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: read
  packages: write
jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          # Setup .npmrc file to publish to npm
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'

      - name: Publish the package
        run: |
          npm config set '//npm.pkg.github.com/:_authToken' "${{ secrets.GITHUB_TOKEN }}"
          npm install
          npm publish

  s3_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'

      - name: Build the bundle
        run: |
          yarn
          yarn dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Look for alternative solution at https://github.com/aws-actions/configure-aws-credentials and
      # https://monicagranbois.com/blog/webdev/use-github-actions-to-deploy-11ty-site-to-s3/
      - name: S3 upload
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'
          SOURCE_DIR: 'dist'
          DEST_DIR: ${{ github.ref_name }}
